/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    lemmari: Lemmari;
    utenti: Utenti;
    'utenti-ruoli-lemmari': UtentiRuoliLemmari;
    lemmi: Lemmi;
    'varianti-grafiche': VariantiGrafiche;
    definizioni: Definizioni;
    fonti: Fonti;
    ricorrenze: Ricorrenze;
    'livelli-razionalita': LivelliRazionalita;
    'riferimenti-incrociati': RiferimentiIncrociati;
    'contenuti-statici': ContenutiStatici;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lemmari".
 */
export interface Lemmari {
  id: number;
  slug: string;
  titolo: string;
  descrizione?: string | null;
  periodo_storico?: string | null;
  attivo?: boolean | null;
  ordine?: number | null;
  configurazione?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  data_pubblicazione?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utenti".
 */
export interface Utenti {
  id: number;
  nome: string;
  cognome: string;
  ruolo: 'super_admin' | 'lemmario_admin' | 'redattore' | 'lettore';
  attivo?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utenti-ruoli-lemmari".
 */
export interface UtentiRuoliLemmari {
  id: number;
  utente: number | Utenti;
  lemmario: number | Lemmari;
  ruolo: 'lemmario_admin' | 'redattore' | 'lettore';
  data_assegnazione?: string | null;
  assegnato_da?: (number | null) | Utenti;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lemmi".
 */
export interface Lemmi {
  id: number;
  lemmario: number | Lemmari;
  termine: string;
  tipo: 'latino' | 'volgare';
  slug?: string | null;
  ordinamento?: string | null;
  note_redazionali?: string | null;
  pubblicato?: boolean | null;
  data_pubblicazione?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "varianti-grafiche".
 */
export interface VariantiGrafiche {
  id: number;
  lemma: number | Lemmi;
  variante: string;
  priorita?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "definizioni".
 */
export interface Definizioni {
  id: number;
  lemma: number | Lemmi;
  numero: number;
  testo: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonti".
 */
export interface Fonti {
  id: number;
  shorthand_id: string;
  titolo: string;
  autore?: string | null;
  anno?: string | null;
  riferimento_completo: string;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ricorrenze".
 */
export interface Ricorrenze {
  id: number;
  definizione: number | Definizioni;
  fonte: number | Fonti;
  testo_originale: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  pagina?: string | null;
  livello_razionalita?: (number | null) | LivelliRazionalita;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livelli-razionalita".
 */
export interface LivelliRazionalita {
  id: number;
  lemmario: number | Lemmari;
  numero: number;
  nome: string;
  descrizione?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "riferimenti-incrociati".
 */
export interface RiferimentiIncrociati {
  id: number;
  lemma_sorgente: number | Lemmi;
  tipo: 'sinonimo' | 'contrario' | 'correlato' | 'vedi_anche';
  lemma_destinazione: number | Lemmi;
  bidirezionale?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenuti-statici".
 */
export interface ContenutiStatici {
  id: number;
  lemmario?: (number | null) | Lemmari;
  slug: string;
  titolo: string;
  contenuto: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  pubblicato?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'utenti';
    value: number | Utenti;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}